# Generated by Django 4.0.2 on 2022-05-19 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_funds1__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funds2',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds3',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds4',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds5',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds6',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds7',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds8',
            name='_id',
        ),
        migrations.RemoveField(
            model_name='funds9',
            name='_id',
        ),
    ]
