# Generated by Django 4.0.2 on 2022-05-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_funds2__id_remove_funds3__id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='funds9',
        ),
        migrations.AddField(
            model_name='funds1',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds2',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds3',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds4',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds5',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds6',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds7',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='funds8',
            name='위험등급',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
